
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jigar Panchal
 */
public class tiktak extends javax.swing.JFrame {

      private String startgame="X";
      private  static   int xcount=0;
      private   static  int ocount=0;
    public tiktak() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtplayer1 = new javax.swing.JLabel();
        txtplayer2 = new javax.swing.JLabel();
        txtreset = new javax.swing.JButton();
        txtexit = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        txtbutton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        txtbutton2 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        txtbutton3 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        txtbutton4 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        txtbutton5 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        txtbutton6 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        txtbutton7 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        txtbutton8 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        txtbutton9 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tic Tac Toe ");

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Tic-tac-toe Game");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(46, 46, 46))
        );

        jLabel2.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Points Tabel");
        jLabel2.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel3.setText("Player1:-");

        jLabel4.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel4.setText("Player2:-");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(109, 109, 109))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtplayer2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtplayer1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addGap(56, 56, 56)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtplayer1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtplayer2))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        txtreset.setBackground(new java.awt.Color(255, 102, 102));
        txtreset.setText("RESET");
        txtreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtresetActionPerformed(evt);
            }
        });

        txtexit.setBackground(new java.awt.Color(255, 102, 102));
        txtexit.setText("EXIT");
        txtexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtexitActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        txtbutton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbutton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(txtbutton1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtbutton1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        txtbutton2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtbutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbutton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(txtbutton2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtbutton2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        txtbutton3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtbutton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbutton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(txtbutton3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtbutton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        txtbutton4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtbutton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbutton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(txtbutton4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtbutton4, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        txtbutton5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtbutton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbutton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(txtbutton5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtbutton5, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        txtbutton6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtbutton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbutton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(txtbutton6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtbutton6, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        txtbutton7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtbutton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbutton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtbutton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtbutton7, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        txtbutton8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtbutton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbutton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(txtbutton8, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtbutton8, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        txtbutton9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtbutton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbutton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(txtbutton9, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtbutton9, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtreset, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(txtexit, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtreset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtexit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    public void gamescore()
    {
        txtplayer1.setText(String.valueOf(xcount));
        txtplayer2.setText(String.valueOf(ocount));
        
    }
    public void chooseplayer()
    {
        if(startgame.equalsIgnoreCase("X"))
        {
            startgame="O";
        }
        else{
          startgame="X";  
        }
    }
    public void winner()
    {
        String b1=txtbutton1.getText();
        String b2=txtbutton2.getText();
        String b3=txtbutton3.getText();
        String b4=txtbutton4.getText();
        String b5=txtbutton5.getText();
        String b6=txtbutton6.getText();
        String b7=txtbutton7.getText();
        String b8=txtbutton8.getText();
        String b9=txtbutton9.getText();
        if(b1==("X")&&b2==("X")&&b3==("X"))
        {
           JOptionPane.showMessageDialog(this,"Player x WInner","tic ton",JOptionPane.INFORMATION_MESSAGE);
           xcount++;
           gamescore();
           txtbutton1.setBackground(Color.GREEN);
           txtbutton2.setBackground(Color.GREEN);
           txtbutton3.setBackground(Color.GREEN);
        }
         if(b4==("X")&&b5==("X")&&b6==("X"))
        {
           JOptionPane.showMessageDialog(this,"Player x WInner","tic ton",JOptionPane.INFORMATION_MESSAGE);
           xcount++;
           gamescore();
           txtbutton4.setBackground(Color.GREEN);
           txtbutton5.setBackground(Color.GREEN);
           txtbutton6.setBackground(Color.GREEN);
        }
          if(b7==("X")&&b8==("X")&&b9==("X"))
        {
           JOptionPane.showMessageDialog(this,"Player x WInner","tic ton",JOptionPane.INFORMATION_MESSAGE);
           xcount++;
           gamescore();
           txtbutton7.setBackground(Color.GREEN);
           txtbutton8.setBackground(Color.GREEN);
           txtbutton9.setBackground(Color.GREEN);
        }
          if(b1==("X")&&b4==("X")&&b7==("X"))
        {
           JOptionPane.showMessageDialog(this,"Player x WInner","tic ton",JOptionPane.INFORMATION_MESSAGE);
           xcount++;
           gamescore();
           txtbutton1.setBackground(Color.GREEN);
           txtbutton4.setBackground(Color.GREEN);
           txtbutton7.setBackground(Color.GREEN);
        }
          if(b2==("X")&&b5==("X")&&b8==("X"))
        {
           JOptionPane.showMessageDialog(this,"Player x WInner","tic ton",JOptionPane.INFORMATION_MESSAGE);
           xcount++;
           gamescore();
           txtbutton2.setBackground(Color.GREEN);
           txtbutton5.setBackground(Color.GREEN);
           txtbutton8.setBackground(Color.GREEN);
        }
          if(b3==("X")&&b6==("X")&&b9==("X"))
        {
           JOptionPane.showMessageDialog(this,"Player x WInner","tic ton",JOptionPane.INFORMATION_MESSAGE);
           xcount++;
           gamescore();
           txtbutton3.setBackground(Color.GREEN);
           txtbutton6.setBackground(Color.GREEN);
           txtbutton9.setBackground(Color.GREEN);
        }
          if(b1==("X")&&b5==("X")&&b9==("X"))
        {
           JOptionPane.showMessageDialog(this,"Player x WInner","tic ton",JOptionPane.INFORMATION_MESSAGE);
           xcount++;
           gamescore();
           txtbutton1.setBackground(Color.GREEN);
           txtbutton5.setBackground(Color.GREEN);
           txtbutton9.setBackground(Color.GREEN);
        }
          if(b3==("X")&&b5==("X")&&b7==("X"))
        {
           JOptionPane.showMessageDialog(this,"Player x WInner","tic ton",JOptionPane.INFORMATION_MESSAGE);
           xcount++;
           gamescore();
           txtbutton3.setBackground(Color.GREEN);
           txtbutton5.setBackground(Color.GREEN);
           txtbutton7.setBackground(Color.GREEN);
        }
            if(b1==("O")&&b2==("O")&&b3==("O"))
        {
           JOptionPane.showMessageDialog(this,"Player 0 WInner","tic ton",JOptionPane.INFORMATION_MESSAGE);
           ocount++;
           gamescore();
           txtbutton1.setBackground(Color.GREEN);
           txtbutton2.setBackground(Color.GREEN);
           txtbutton3.setBackground(Color.GREEN);
        }
             if(b3==("O")&&b5==("O")&&b7==("O"))
        {
           JOptionPane.showMessageDialog(this,"Player O WInner","tic ton",JOptionPane.INFORMATION_MESSAGE);
           ocount++;
           gamescore();
           txtbutton3.setBackground(Color.GREEN);
           txtbutton5.setBackground(Color.GREEN);
           txtbutton7.setBackground(Color.GREEN);
        }
              if(b1==("O")&&b5==("O")&&b9==("O"))
        {
           JOptionPane.showMessageDialog(this,"Player O WInner","tic ton",JOptionPane.INFORMATION_MESSAGE);
           ocount++;
           gamescore();
           txtbutton1.setBackground(Color.GREEN);
           txtbutton5.setBackground(Color.GREEN);
           txtbutton9.setBackground(Color.GREEN);
        }
               if(b3==("O")&&b6==("O")&&b9==("O"))
        {
           JOptionPane.showMessageDialog(this,"Player O WInner","tic ton",JOptionPane.INFORMATION_MESSAGE);
           ocount++;
           gamescore();
           txtbutton3.setBackground(Color.GREEN);
           txtbutton6.setBackground(Color.GREEN);
           txtbutton9.setBackground(Color.GREEN);
        }
                 if(b2==("O")&&b5==("O")&&b8==("O"))
        {
           JOptionPane.showMessageDialog(this,"Player O WInner","tic ton",JOptionPane.INFORMATION_MESSAGE);
           ocount++;
           gamescore();
           txtbutton2.setBackground(Color.GREEN);
           txtbutton5.setBackground(Color.GREEN);
           txtbutton8.setBackground(Color.GREEN);
        }
         if(b7==("O")&&b8==("O")&&b9==("O"))
        {
           JOptionPane.showMessageDialog(this,"Player O WInner","tic ton",JOptionPane.INFORMATION_MESSAGE);
           ocount++;
           gamescore();
           txtbutton7.setBackground(Color.GREEN);
           txtbutton8.setBackground(Color.GREEN);
           txtbutton9.setBackground(Color.GREEN);
        }
          if(b1==("O")&&b4==("O")&&b7==("O"))
        {
           JOptionPane.showMessageDialog(this,"Player O WInner","tic ton",JOptionPane.INFORMATION_MESSAGE);
           ocount++;
           gamescore();
           txtbutton1.setBackground(Color.GREEN);
           txtbutton4.setBackground(Color.GREEN);
           txtbutton7.setBackground(Color.GREEN);
        }
           if(b1==("O")&&b2==("O")&&b3==("O"))
        {
           JOptionPane.showMessageDialog(this,"Player O WInner","tic ton",JOptionPane.INFORMATION_MESSAGE);
           ocount++;
           gamescore();
           txtbutton1.setBackground(Color.GREEN);
           txtbutton2.setBackground(Color.GREEN);
           txtbutton3.setBackground(Color.GREEN);
        }
         if(b4==("O")&&b5==("O")&&b6==("O"))
        {
           JOptionPane.showMessageDialog(this,"Player O WInner","tic ton",JOptionPane.INFORMATION_MESSAGE);
           ocount++;
           gamescore();
           txtbutton4.setBackground(Color.GREEN);
           txtbutton5.setBackground(Color.GREEN);
           txtbutton6.setBackground(Color.GREEN);
        }
        
    }
    private void txtbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbutton1ActionPerformed
        txtbutton1.setText(startgame);
        if(startgame.equalsIgnoreCase("X"))
        {
            startgame="O";
        }
        else{
          startgame="X";  
        }
        chooseplayer();
        winner();
    }//GEN-LAST:event_txtbutton1ActionPerformed

    private void txtbutton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbutton7ActionPerformed
        // TODO add your handling code here:
                 txtbutton7.setText(startgame);
        if(startgame.equalsIgnoreCase("X"))
        {
            txtbutton7.setForeground(Color.red);
        }
        else{ 
          txtbutton7.setForeground(Color.MAGENTA);
        }
        chooseplayer();
        winner();

    }//GEN-LAST:event_txtbutton7ActionPerformed

    private void txtbutton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbutton4ActionPerformed
                 txtbutton4.setText(startgame);
        if(startgame.equalsIgnoreCase("X"))
        {
            txtbutton4.setForeground(Color.red);
        }
        else{ 
          txtbutton4.setForeground(Color.MAGENTA);
        }
        chooseplayer();
        winner();

    }//GEN-LAST:event_txtbutton4ActionPerformed

    private void txtbutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbutton2ActionPerformed
        // TODO add your handling code here:
         txtbutton2.setText(startgame);
        if(startgame.equalsIgnoreCase("X"))
        {
            txtbutton2.setForeground(Color.red);
        }
        else{ 
          txtbutton2.setForeground(Color.MAGENTA);
        }
        chooseplayer();
        winner();
    }//GEN-LAST:event_txtbutton2ActionPerformed

    private void txtexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtexitActionPerformed
        JFrame j=new JFrame("EXIT");
     if  (JOptionPane.showConfirmDialog(j,"are you exit from   game?","tic tak",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
     {
         System.exit(0);
     }
     
    }//GEN-LAST:event_txtexitActionPerformed

    private void txtbutton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbutton3ActionPerformed
        // TODO add your handling code here:
         txtbutton3.setText(startgame);
          if(startgame.equalsIgnoreCase("X"))
        {
            txtbutton3.setForeground(Color.red);
        }
        else{ 
          txtbutton4.setForeground(Color.MAGENTA);
        }
        chooseplayer();
        winner();
        
    }//GEN-LAST:event_txtbutton3ActionPerformed

    private void txtbutton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbutton5ActionPerformed
        // TODO add your handling code here:
                 txtbutton5.setText(startgame);
        if(startgame.equalsIgnoreCase("X"))
        {
            txtbutton5.setForeground(Color.red);
        }
        else{ 
          txtbutton5.setForeground(Color.MAGENTA);
        }
        chooseplayer();
        winner();

    }//GEN-LAST:event_txtbutton5ActionPerformed

    private void txtbutton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbutton6ActionPerformed
        // TODO add your handling code here:
                 txtbutton6.setText(startgame);
        if(startgame.equalsIgnoreCase("X"))
        {
            txtbutton6.setForeground(Color.red);
        }
        else{ 
          txtbutton6.setForeground(Color.MAGENTA);
        }
        chooseplayer();
        winner();

    }//GEN-LAST:event_txtbutton6ActionPerformed

    private void txtbutton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbutton8ActionPerformed
        // TODO add your handling code here:
                 txtbutton8.setText(startgame);
        if(startgame.equalsIgnoreCase("X"))
        {
            txtbutton8.setForeground(Color.red);
        }
        else{ 
          txtbutton8.setForeground(Color.MAGENTA);
        }
        chooseplayer();
        winner();

    }//GEN-LAST:event_txtbutton8ActionPerformed

    private void txtbutton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbutton9ActionPerformed
        // TODO add your handling code here:
                 txtbutton9.setText(startgame);
        if(startgame.equalsIgnoreCase("X"))
        {
            txtbutton9.setForeground(Color.red);
        }
        else{ 
          txtbutton9.setForeground(Color.MAGENTA);
        }
        chooseplayer();
        winner();

    }//GEN-LAST:event_txtbutton9ActionPerformed

    private void txtresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtresetActionPerformed
        //TODO add your handling code here:
        txtbutton1.setText(null);
        txtbutton2.setText(null);
        txtbutton3.setText(null);
        txtbutton4.setText(null);
        txtbutton5.setText(null);
        txtbutton6.setText(null);
        txtbutton7.setText(null);
        txtbutton8.setText(null);
        txtbutton9.setText(null);
        txtbutton1.setBackground(Color.LIGHT_GRAY);
        txtbutton2.setBackground(Color.LIGHT_GRAY);
        txtbutton3.setBackground(Color.LIGHT_GRAY);
        txtbutton4.setBackground(Color.LIGHT_GRAY);
        txtbutton5.setBackground(Color.LIGHT_GRAY);
        txtbutton6.setBackground(Color.LIGHT_GRAY);
        txtbutton7.setBackground(Color.LIGHT_GRAY);
        txtbutton8.setBackground(Color.LIGHT_GRAY);
        txtbutton9.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_txtresetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tiktak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tiktak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tiktak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tiktak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tiktak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton txtbutton1;
    private javax.swing.JButton txtbutton2;
    private javax.swing.JButton txtbutton3;
    private javax.swing.JButton txtbutton4;
    private javax.swing.JButton txtbutton5;
    private javax.swing.JButton txtbutton6;
    private javax.swing.JButton txtbutton7;
    private javax.swing.JButton txtbutton8;
    private javax.swing.JButton txtbutton9;
    private javax.swing.JButton txtexit;
    private javax.swing.JLabel txtplayer1;
    private javax.swing.JLabel txtplayer2;
    private javax.swing.JButton txtreset;
    // End of variables declaration//GEN-END:variables
}
